### ISSUE TITLE
docker-entrypoint.sh fails when using SSL and restarting the container

### ISSUE THREAD

**Issue by fmoraes74** [scholzj/docker-qpid-cpp#4]
I am using docker-compose to bring up a server along with a responder process. It works great the first time, but if I attempt to restart the container, there is an error coming from the entry point script:

```
certutil: could not find certificate named "serverKey": SEC_ERROR_UNRECOGNIZED_OID: Unrecognized Object Identifier.
```
Also, there is another error that doesn't cause an immediate issue:

```
/docker-entrypoint.sh: line 294: [: -eq: unary operator expected
```

For reference, this a sample docker compose that I am using:

```
version: '2'

services:
  qpid-cpp:
    image: 'scholzj/qpid-cpp'
    ports:
      - '5671:5671'
      - '5672:5672'
    volumes:
      - 'amqp_data:/var/lib/qpidd/store'
    environment:
      - QPIDD_ADMIN_USERNAME=admin
      - QPIDD_ADMIN_PASSWORD=password
      - "QPIDD_SSL_SERVER_PUBLIC_KEY=-----BEGIN CERTIFICATE-----\n\
       ...\
       -----END CERTIFICATE-----\n"
      - "QPIDD_SSL_SERVER_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\n\
      ...\
       -----END RSA PRIVATE KEY-----\n"

volumes:
  amqp_data:
    driver: local
```

To recreate, bring up the container using `docker-compose up`. After it starts, bring it down by pressing `Ctrl+C` and attempt to bring it up once again. It should hit the failure due this code:

```
        # Delete old server keys
        exists=$(certutil -L -d sql:$QPIDD_SSL_DB_DIR | grep serverKey | wc -l)
        while [ "$exists" -gt 0 ]; do
            certutil -D -d sql:$QPIDD_SSL_DB_DIR -n serverKey
            res=$?
        done
```
The `while` loop checks `$exists` but this seems like should only execute once or update `$exists` inside the loop.
